feat: Statistic service
emtpy61/java-explore-with-me pull request #1
Opened 2023-09-06 21:24 UTC by emtpy61

- Реализовать сервис статистики в соответствии со спецификацией: [ewm-stats-service.json](https://raw.githubusercontent.com/yandex-praktikum/java-explore-with-me/main/ewm-stats-service-spec.json).
- Реализовать HTTP-клиент для работы с сервисом статистики.
- Подготовить сборку проекта.

2023-09-07 19:56 UTC, alexache requested changes

2023-09-07 19:56 UTC, alexache commented on ewm-main-service/pom.xml
> +            <version>1.5.5.Final</version>
версии зависимостей должны быть в родительском модуле

2023-09-07 19:56 UTC, alexache commented on ewm-stats-service/client/pom.xml
> +            <artifactId>stat_dto</artifactId>
в названиях артифактов/модулей принятно слова разделять через тире, а не нижнее подчеркивание

2023-09-07 19:56 UTC, alexache commented on ewm-stats-service/client/src/main/java/ru/practicum/stat_client/StatisticClient.java
> +            parameters.put("uris", uris);
uris лучше переделать в строку с разделением через запятую - String.join()

2023-09-07 19:56 UTC, alexache commented on ewm-stats-service/dto/src/main/java/ru/practicum/stat_dto/EndpointHitDto.java
> +    private String app;
Может стоит добавить валидаций?

2023-09-07 19:56 UTC, alexache commented on ewm-stats-service/server/pom.xml
> +            <version>1.5.5.Final</version>
версии зависимостей в родительский модуль

2023-09-07 19:56 UTC, alexache commented on ewm-stats-service/server/pom.xml
> +                <version>3.11.0</version>
версии плагинов тоже в родительский модуль

2023-09-07 19:56 UTC, alexache commented on ewm-stats-service/server/src/main/java/ru/practicum/stat_svc/controller/StatisticController.java
> +@Validated
но валидаций нет?

2023-09-07 19:56 UTC, alexache commented on ewm-stats-service/server/src/main/java/ru/practicum/stat_svc/mapper/EndpointHitMapper.java
> +@Generated
Лишняя аннотация

2023-09-07 19:56 UTC, alexache commented on ewm-stats-service/server/src/main/resources/schema.sql
> +    ip VARCHAR(255)  NOT NULL,
длинный, однако, айпишник

2023-09-08 18:15 UTC, emtpy61 commented on ewm-stats-service/server/src/main/resources/schema.sql
> +    ip VARCHAR(255)  NOT NULL,
поправил.

2023-09-08 18:18 UTC, emtpy61 commented on ewm-stats-service/server/src/main/java/ru/practicum/stat_svc/mapper/EndpointHitMapper.java
> +@Generated
поправил

2023-09-08 18:58 UTC, emtpy61 commented on ewm-main-service/pom.xml
> +            <version>1.5.5.Final</version>
поправил

2023-09-08 18:58 UTC, emtpy61 commented on ewm-stats-service/server/pom.xml
> +            <version>1.5.5.Final</version>
поправил

2023-09-08 18:58 UTC, emtpy61 commented on ewm-stats-service/server/pom.xml
> +                <version>3.11.0</version>
поправил

2023-09-08 19:01 UTC, emtpy61 commented on ewm-stats-service/server/src/main/java/ru/practicum/stat_svc/controller/StatisticController.java
> +@Validated
Они были 😅. Но потом решил что сам с собой контракт не нарушишь. 😀
Добавил.

2023-09-08 19:01 UTC, emtpy61 commented on ewm-stats-service/dto/src/main/java/ru/practicum/stat_dto/EndpointHitDto.java
> +    private String app;
Добавил.

2023-09-08 19:02 UTC, emtpy61 commented on ewm-stats-service/client/pom.xml
> +            <artifactId>stat_dto</artifactId>
поменял

2023-09-08 19:03 UTC, emtpy61 commented on ewm-stats-service/client/src/main/java/ru/practicum/stat_client/StatisticClient.java
> +            parameters.put("uris", uris);
поправил

2023-09-09 21:41 UTC, alexache commented on ewm-stats-service/server/src/main/java/ru/practicum/stat_svc/controller/StatisticController.java
> +@Validated
Нет больших вредителей, чем сами разработчики, что-то может забываться

2023-09-09 21:48 UTC, alexache approved these changes

2023-09-09 21:48 UTC, alexache commented on pom.xml
> +	<dependencies>
Более правильно все же dependencyManagement

2023-09-10 09:16 UTC, merged