feat: Main service
emtpy61/java-explore-with-me pull request #2
Opened 2023-09-17 22:15 UTC by emtpy61

Всё необходимое для работы продукта;

2023-09-19 13:01 UTC, alexache requested changes

2023-09-19 13:01 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/MainServerApplication.java
> +    public RestTemplate restTemplate(RestTemplateBuilder builder) {
(опционально) Чаще принято выносить бины в отдельные классы-конфигурации, помечаемые как @Configuration

2023-09-19 13:01 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/controller/AdminApiController.java
> +
Лишняя строка

2023-09-19 13:01 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/controller/pub/CategoriesApiController.java
> +public class CategoriesApiController {
Не хватает @Validated на классе

2023-09-19 13:01 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/controller/pub/CompilationsApiController.java
> +@Slf4j
И в других контроллерах тоже не хватает @Validated

2023-09-19 13:01 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/controller/pub/EventsApiController.java
> +                request);
лучше не выносить данный объект в сервис, а передать только необходимые поля

2023-09-19 13:01 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/model/Event.java
> +    private int confirmedRequests;
Это не должно храниться в таблице события иначе будет дублировать другую таблицу

2023-09-19 13:01 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/model/Event.java
> +    private Long views;
Это не должно храниться в таблице события, а получаться из сервиса статистики

2023-09-19 13:01 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/CompilationServiceImpl.java
> +            compilation.setEvents(new HashSet<>(events));
А что даст хэшсет из объектов без переопределенных equals/hashcode? Может лучше оставить лист?

2023-09-19 13:01 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/RequestServiceImpl.java
> +        long requests = requestRepository.countByEventIdAndStatus(eventId, RequestStatus.CONFIRMED);
А зачем повторный запрос как и выше для confirmedRequests?

2023-09-19 13:01 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/RequestServiceImpl.java
> +            event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Это лишнее

2023-09-19 13:01 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/RequestServiceImpl.java
> +            if (request.getStatus().equals(RequestStatus.REJECTED)) {
Если нужен статус  PENDING, то почему на него бы и не проверять?

2023-09-21 17:40 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/controller/pub/EventsApiController.java
> +                request);
Поправил

2023-09-21 17:44 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/CompilationServiceImpl.java
> +            compilation.setEvents(new HashSet<>(events));
оставил

2023-09-21 21:54 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/model/Event.java
> +    private int confirmedRequests;
поправил

2023-09-21 22:05 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/RequestServiceImpl.java
> +            event.setConfirmedRequests(event.getConfirmedRequests() + 1);
убрал

2023-09-21 22:05 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/RequestServiceImpl.java
> +        long requests = requestRepository.countByEventIdAndStatus(eventId, RequestStatus.CONFIRMED);
убрал

2023-09-21 22:05 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/model/Event.java
> +    private Long views;
убрал

2023-09-21 22:05 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/controller/pub/CompilationsApiController.java
> +@Slf4j
Добавил

2023-09-21 22:06 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/controller/pub/CategoriesApiController.java
> +public class CategoriesApiController {
Добавил

2023-09-21 22:06 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/controller/AdminApiController.java
> +
поправил

2023-09-21 22:15 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/RequestServiceImpl.java
> +            if (request.getStatus().equals(RequestStatus.REJECTED)) {
Поправил

2023-09-21 23:21 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/MainServerApplication.java
> +    public RestTemplate restTemplate(RestTemplateBuilder builder) {
вынес

2023-09-22 18:46 UTC, alexache approved these changes

2023-09-22 18:46 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/EventServiceImpl.java
> +            events.sort(Comparator.comparing(Event::getViews));
сортировка до добавления количества просмотров?

2023-09-23 04:34 UTC, merged