feat: Feature Comments
emtpy61/java-explore-with-me pull request #3
Opened 2023-09-23 08:09 UTC by emtpy61

Функциональность Комментарии

2023-09-24 16:25 UTC, alexache requested changes

2023-09-24 16:25 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/controller/AdminApiController.java
> +    }
Можно еще предусмотреть "модерацию" - редактирование комментария админом

2023-09-24 16:25 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/CommentServiceImpl.java
> +        if (!comment.getAuthor().equals(user)) {
может лучше все же сравнивать по айди юзера?

2023-09-24 16:25 UTC, alexache commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/CommentServiceImpl.java
> +        }
(опционально) по желанию можно было бы поставить проверку и по тому, есть ли  заявка данного пользователя на участии в событии, но это если хочется разрешить комментарии только тем, кто сходил на событие

2023-09-24 20:20 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/controller/AdminApiController.java
> +    }
Добавил

2023-09-24 20:23 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/CommentServiceImpl.java
> +        if (!comment.getAuthor().equals(user)) {
Да так будет лучше😀. Поправил

2023-09-24 21:40 UTC, emtpy61 commented on ewm-main-service/src/main/java/ru/practicum/main_svc/service/impl/CommentServiceImpl.java
> +        }
добавил. поправил тесты под изменение.

2023-09-25 17:38 UTC, alexache approved these changes

2023-09-25 18:32 UTC, merged